<h2>
    Créez votre compte !
</h2>

<form class="pad10 needs-validation" method="post">
    <?php csrf_token()?>
    <div class="form-group row">
        <label for="email" class="col-lg-4 col-form-label">Email:</label>
        <div class="col-lg-7">
            <input type="email" class="form-control" id="email"
             placeholder="Entrez votre adresse email"  name="email" required>
        </div>
    </div>
    <div class="form-group row">
        <label for="password" class=" col-lg-4  col-form-label">Mot de passe:</label>
        <div class="col-lg-7">
            <input type="password" class="form-control" id="password"
             placeholder="Saisissez un mot de passe" name="password" required>
        </div>
    </div>
    <div class="form-group row">
        <label for="password_confirm" class=" col-lg-4  col-form-label">Confirmation du mot de passe:</label>
        <div class="col-lg-7">
            <input type="password" class="form-control" id="password_confirm"
                   placeholder="Ressaisissez votre mot de passe" name="password_confirm" required>
        </div>
    </div>
    <form class="form-group row ">
        <div class="col-sm-10 taright">
            <button type="submit" class="btn btn-primary" name="update">S'inscrire</button>
        </div>
    </form>
</form>
<br>
